# Sequences must be FASTA and metadata must be TSV
# Both files must be zstd compressed
sequences_url: ""
metadata_url: ""

strain_id_field: "accession"

filter:
  group_by: "country year month"
  sequences_per_group: 40
  min_date: 2004
  min_length: 7706

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "region country"
  sampling_bias_correction: 3
